language: node_js
node_js:
  - 10

install: npm i
cache: npm

jobs:
  include:
    - stage: Build
      script: npm run build
      name: "Build"
    # - script: npm run lint
    - script: eslint src --ext .js,.ts
      name: "Lint"
    # - stage: Test
    #   script: npm run unit:interpreter
    #   name: "Interpreter"
